# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: qloapps-db
    ports:
      - 0.0.0.0:3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin
    restart: always
    ports:
     - 9000:80
    volumes:
     - /sessions
    depends_on: 
      - db
    
  apache:
    build: ./php
    volumes:
      - ./apache/www:/app
    environment:
      WEB_DOCUMENT_INDEX: index.php
      WEB_DOCUMENT_ROOT: /app
    ports:
      - 80:80
    
