# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: qloapps-db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  apache:
    build: ./php
    volumes:
      - ./apache/www:/app
    environment:
      WEB_DOCUMENT_INDEX: index.php
      WEB_DOCUMENT_ROOT: /app
    ports:
      - 80:80
    
