FROM webdevops/php-apache:5.6

RUN apt-get update && \
	apt-get install -y libmcrypt-dev

#RUN pecl channel-update pecl.php.net && \
#	pecl install mcrypt-1.0.1

#RUN echo extension=mcrypt.so >> /etc/php/5.6/cli/php.ini
